config/routes.rb
Catarse::Application.routes.draw do
  def ssl_options
    if Rails.env.production? && CatarseSettings.get_without_cache(:secure_host)
      {protocol: 'https', host: CatarseSettings.get_without_cache(:secure_host)}
    else
      {}
    end
  end

  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  devise_for(
    :users,
    {
      path: '',
      path_names:   { sign_in: :login, sign_out: :logout, sign_up: :sign_up },
      controllers:  { omniauth_callbacks: :omniauth_callbacks, passwords: :passwords },
      defaults: ssl_options
    }
  )

  devise_scope :user do
    post '/sign_up', {to: 'devise/registrations#create', as: :sign_up}.merge(ssl_options)
  end

  get '/thank_you' => "static#thank_you"
  match 'users/:user_id/oauth', to: 'users#oauth', via: :all


  filter :locale, exclude: /\/auth\//

  #mount CatarsePaypalExpress::Engine => "/", as: :catarse_paypal_express
  #mount CatarseMoip::Engine => "/", as: :catarse_moip
  mount CatarseCredits::Engine => "/", as: :catarse_credits
  mount CatarsePagarme::Engine => "/", as: :catarse_pagarme
  mount CatarseWepay::Engine => "/", as: :catarse_wepay

  get '/post_preview' => 'post_preview#show', as: :post_preview
  resources :auto_complete_projects, only: [:index]
  resources :projects, only: [:index, :create, :update, :new, :show] do
    resources :posts, controller: 'projects/posts', only: [ :index, :create, :destroy ]
    resources :rewards, only: [ :index, :create, :update, :destroy, :new, :edit ] do
      member do
        post 'sort'
      end
    end
    resources :contributions, {controller: 'projects/contributions'}.merge(ssl_options) do
      member do
        put 'credits_checkout'
      end
    end
    collection do
      get 'video'
    end
    member do
      get :reminder, to: 'projects/reminders#create'
      delete :reminder, to: 'projects/reminders#destroy'
      get :metrics, to: 'projects/metrics#index'
      put 'pay'
      get 'embed'
      get 'video_embed'
      get 'embed_panel'
      get 'send_to_analysis'
    end
  end
  resources :users do
    resources :projects, controller: 'users/projects', only: [ :index ]
    resources :credit_cards, controller: 'users/credit_cards', only: [ :destroy ]
    member do
      get :unsubscribe_notifications
      get :credits
      get :reactivate
    end
    resources :contributions, controller: 'users/contributions', only: [:index] do
      member do
        get :request_refund
      end
    end

    resources :unsubscribes, only: [:create]
    member do
      get 'projects'
      put 'unsubscribe_update'
      put 'update_email'
      put 'update_password', ssl_options
    end
  end

  get "/terms-of-use" => 'high_voltage/pages#show', id: 'terms_of_use'
  get "/privacy-policy" => 'high_voltage/pages#show', id: 'privacy_policy'
  get "/start" => 'high_voltage/pages#show', id: 'start'


  # Channels
  constraints SubdomainConstraint do
    namespace :channels, path: '' do

      namespace :admin do
        namespace :reports do
          resources :subscriber_reports, only: [ :index ]
        end
        resources :posts
        resources :partners
        resources :followers, only: [ :index ]
      end

      resources :posts
      get '/', to: 'profiles#show', as: :profile
      get '/how-it-works', to: 'profiles#how_it_works', as: :about
      resource :profile
      # NOTE We use index instead of create to subscribe comming back from auth via GET
      resource :channels_subscriber, only: [:show, :destroy], as: :subscriber
    end
  end

  # Root path should be after channel constraints
  root to: 'projects#index'

  get "/explore" => "explore#index", as: :explore

  namespace :reports do
    resources :contribution_reports_for_project_owners, only: [:index]
  end

  # Feedback form
  resources :feedbacks, only: [:create]

  namespace :admin do
    resources :projects, only: [ :index, :update, :destroy ] do
      member do
        put 'approve'
        put 'reject'
        put 'push_to_draft'
        put 'push_to_trash'
      end
    end

    resources :statistics, only: [ :index ]
    resources :financials, only: [ :index ]

    resources :contributions, only: [ :index, :update, :show ] do
      member do
        get :second_slip
        put 'confirm'
        put 'pendent'
        put 'change_reward'
        put 'refund'
        put 'hide'
        put 'cancel'
        put 'push_to_trash'
      end
    end
    resources :users, only: [ :index ]

    namespace :reports do
      resources :contribution_reports, only: [ :index ]
    end
  end

  get "/:permalink" => "projects#show", as: :project_by_slug

end

app/models/concerns/project/custom_validators.rb
module Project::CustomValidators
  extend ActiveSupport::Concern

  included do
    validate :permalink_cant_be_route, allow_nil: true

    def self.permalink_on_routes?(permalink)
      permalink && self.get_routes.include?(permalink.downcase)
    end

    def permalink_cant_be_route
      errors.add(:permalink, I18n.t("activerecord.errors.models.project.attributes.permalink.invalid")) if Project.permalink_on_routes?(permalink)
    end
  end
end

app/models/concerns/project/reminders_handler.rb
module Project::RemindersHandler
  extend ActiveSupport::Concern

  included do
    def user_already_in_reminder?(user_id)
      notifications.where(template_name: 'reminder', user_id: user_id).present? ||
      user_in_reminder_queue?(user_id)
    end

    def user_in_reminder_queue?(user_id)
      scheduler_set.any? do |job|
        job_matches?(job, user_id)
      end
    end

    def delete_from_reminder_queue(user_id)
      job = scheduler_set.select do |job|
        job_matches?(job, user_id)
      end

      job.each(&:delete)
    end

    def job_matches?(job, user_id)
      job['class'] == 'ReminderProjectWorker' &&
      job.args[0] == user_id &&
      job.args[1] == self.id
    end

    def scheduler_set
      @queue_set ||= Sidekiq::ScheduledSet.new
    end
  end
end

app/models/concerns/project/video_handler.rb
module Project::VideoHandler
  extend ActiveSupport::Concern
  include Shared::VideoHandler

  included do
    mount_uploader :video_thumbnail, ProjectUploader

    def download_video_thumbnail
      self.video_thumbnail = open(self.video.thumbnail_large)  if self.video_valid?
      self.save
    rescue OpenURI::HTTPError, TypeError => e
      Rails.logger.info "-----> #{e.inspect}"
    end
  end
end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < Admin::BaseController
  layout 'catarse_bootstrap'

  has_scope :by_user_email, :by_id, :pg_search, :user_name_contains, :with_state, :by_category_id, :order_by, :by_channel
  has_scope :between_created_at, :between_expires_at, :between_online_date, :between_updated_at, :goal_between, using: [ :start_at, :ends_at ]

  before_filter do
    @total_projects = Project.count(:all)
  end

  [:approve, :reject, :push_to_draft, :push_to_trash].each do |name|
    define_method name do
      @project = Project.find params[:id]
      @project.send("#{name.to_s}!")
      redirect_to :back
    end
  end

  def destroy
    @project = Project.find params[:id]
    if @project.can_push_to_trash?
      @project.push_to_trash!
    end

    redirect_to admin_projects_path
  end

  protected
  def collection
    @scoped_projects = apply_scopes(end_of_association_chain).with_project_totals.without_state('deleted')
    @projects = @scoped_projects.page(params[:page])
  end
end

app/controllers/projects/contributions_controller.rb
class Projects::ContributionsController < ApplicationController
  inherit_resources
  actions :index, :show, :new, :update, :review, :create
  skip_before_filter :force_http
  skip_before_filter :verify_authenticity_token, only: [:moip]
  has_scope :available_to_count, type: :boolean
  has_scope :with_state
  has_scope :page, default: 1
  after_filter :verify_authorized, except: [:index]
  belongs_to :project
  before_filter :detect_old_browsers, only: [:new, :create]

  helper_method :avaiable_payment_engines

  def edit
    authorize resource
    if resource.reward.try(:sold_out?)
      flash[:alert] = t('.reward_sold_out')
      return redirect_to new_project_contribution_path(@project)
    end
  end

  def update
    authorize resource
    resource.update_attributes(permitted_params[:contribution])
    resource.update_user_billing_info
    render json: {message: 'updated'}
  end

  def index
    render collection
  end

  def show
    authorize resource
    @title = t('projects.contributions.show.title')
  end

  def new
    @contribution = Contribution.new(project: parent, user: current_user)
    authorize @contribution

    @title = t('projects.contributions.new.title', name: @project.name)
    empty_reward = Reward.new(minimum_value: 0, description: t('projects.contributions.new.no_reward'))
    @rewards = [empty_reward] + @project.rewards.remaining.order(:minimum_value)

    # Select
    if params[:reward_id] && (@selected_reward = @project.rewards.find params[:reward_id]) && !@selected_reward.sold_out?
      @contribution.reward = @selected_reward
      @contribution.value = "%0.0f" % @selected_reward.minimum_value
    end
  end

  def create
    @title = t('projects.contributions.create.title')
    @contribution = Contribution.new(params[:contribution].merge(user: current_user, project: parent))
    @contribution.reward_id = nil if params[:contribution][:reward_id].to_i == 0
    authorize @contribution
    create! do |success,failure|
      failure.html do
        flash[:alert] = resource.errors.full_messages.to_sentence
        return redirect_to new_project_contribution_path(@project)
      end
      success.html do
        resource.update_current_billing_info
        flash[:notice] = nil
        session[:thank_you_contribution_id] = @contribution.id
        return redirect_to edit_project_contribution_path(project_id: @project.id, id: @contribution.id)
      end
    end
    @thank_you_id = @project.id
  end

  protected
  def permitted_params
    params.permit(policy(resource).permitted_attributes)
  end

  def avaiable_payment_engines
    engines = []

    if resource.value < 0
      engines.push PaymentEngines.find_engine('Credits')
    else
      if parent.using_pagarme?
        engines.push PaymentEngines.find_engine('Pagarme')
      else
        engines = PaymentEngines.engines.inject([]) do |total, item|
          if item.name != 'Credits' && item.name != 'Pagarme'
            total << item
          end
#          if item.name == 'Credits' && current_user.credits > 0
#            total << item
#          elsif !item.name.match(/(Credits|Pagarme)/)
#            total << item
#          end

          total
        end
      end
    end

    @engines ||= engines
  end

  def collection
    @contributions ||= apply_scopes(end_of_association_chain).available_to_display.order("confirmed_at DESC").per(10)
  end
end

app/controllers/projects/metrics_controller.rb
class Projects::MetricsController < ApplicationController
  after_filter :verify_authorized
  respond_to :html
  layout false

  def index
    authorize parent

    @metrics ||= {}

    confirmed_amount_by_day
    total_confirmed_by_day
    total_by_address_state
    respond_with @metrics
  end

  protected

  def total_by_address_state
    @metrics[:address_state] = collection.with_state('confirmed').
      joins(:user).group("upper(users.address_state)").count
  end

  def total_confirmed_by_day
    @metrics[:confirmed] = collection.with_state('confirmed').
      group("contributions.created_at::date").
      count
  end

  def confirmed_amount_by_day
    @metrics[:confirmed_amount_by_day] = collection.with_state('confirmed').
      group("contributions.created_at::date").
      sum(:value)
  end

  def collection
    @contributions ||= parent.contributions.
      where.not("contributions.created_at::date = current_timestamp::date")
  end

  def parent
    @project ||= Project.find params[:id]
  end

end

app/controllers/projects/posts_controller.rb
class Projects::PostsController < ApplicationController
  after_filter :verify_authorized, except: %i[index show]
  after_action :verify_policy_scoped, only: %i[index]
  inherit_resources

  actions :index, :create, :destroy
  belongs_to :project

  def show
    render resource
  end

  def index
    render collection.page(params[:page]).per(3)
  end

  def create
    @post = parent.posts.new(post_params)
    authorize @post
    @post.save
    render @post
  end

  def destroy
    authorize resource
    destroy!{ return index }
  end

  def collection
    @posts ||= policy_scope(end_of_association_chain).ordered
  end

  protected

  def post_params
    params.require(:project_post).permit(:title, :comment, :user_id, :exclusive).merge!(user_id: current_user.try(:id))
  end

end

app/controllers/projects/reminders_controller.rb
class Projects::RemindersController < ApplicationController
  before_filter :authenticate_user!

  def create
    unless current_user.has_valid_contribution_for_project?(params[:id]) && project.user_already_in_reminder?(current_user.id)
      reminder_at = project.expires_at - 48.hours
      ReminderProjectWorker.perform_at(reminder_at, current_user.id, project.id)
    end
    flash[:notice] = t('projects.reminder.ok')
    redirect_to project_by_slug_path(project.permalink)
  end

  def destroy
    project.notifications.where(template_name: 'reminder', user_id: current_user.id).destroy_all
    project.delete_from_reminder_queue(current_user.id)

    redirect_to project_by_slug_path(project.permalink)
  end


  protected

  def project
    @project ||= Project.find params[:id]
  end
end

app/controllers/projects_controller.rb
# coding: utf-8
class ProjectsController < ApplicationController
  after_filter :verify_authorized, except: %i[index video video_embed embed embed_panel]
  inherit_resources
  has_scope :pg_search, :by_category_id, :near_of
  has_scope :recent, :expiring, :successful, :in_funding, :recommended, :not_expired, type: :boolean

  respond_to :html
  respond_to :json, only: [:index, :show, :update]
  def index
    @location = ""

    unless params[:location].blank?
      @location = params[:location]
    else
      @location = current_user.school if current_user
    end

    index! do |format|
      format.html do
        if request.xhr?
          @projects = apply_scopes(Project.visible.order_status)
            .most_recent_first
            .includes(:project_total, :user, :category)
            .page(params[:page]).per(6)
          return render partial: 'project', collection: @projects, layout: false
        else
          @title = t("site.title")
          @recommends = ProjectsForHome.recommends.includes(:project_total)  
          unless @location.blank? #params[:location] != "" || current_user
            @projects_near = Project.with_state('online').near_of(@location).order("random()").limit(3).includes(:project_total)
          end
          @expiring = ProjectsForHome.expiring.includes(:project_total)
          @recent   = ProjectsForHome.recents.includes(:project_total)
        end
      end
    end
  end

  def new
    @project = Project.new user: current_user
    authorize @project
    @title = t('projects.new.title')
    @project.rewards.build
  end

  def create
    @project = Project.new params[:project].merge(user: current_user)
    authorize @project
    create! { project_by_slug_path(@project.permalink) }
  end

  def destroy
    authorize resource
    destroy!
  end

  def send_to_analysis
    authorize resource
    resource.send_to_analysis
    if referal_link.present?
      resource.update_attribute :referal_link, referal_link
    end
    flash[:notice] = t('projects.send_to_analysis')
    redirect_to project_by_slug_path(@project.permalink)
  end

  def update
    authorize resource
    update! do |format|
      format.html do
        if resource.errors.present?
          flash[:alert] = resource.errors.full_messages.to_sentence
        else
          flash[:notice] = t('project.update.success')
        end

        redirect_to project_by_slug_path(@project.reload.permalink, anchor: 'edit')
      end
    end
  end

  def show
    @title = resource.name
    authorize @project
    fb_admins_add(resource.user.facebook_id) if resource.user.facebook_id
    @posts_count = resource.posts.count(:all)
    @post = resource.posts.where(id: params[:project_post_id]).first if params[:project_post_id].present?
  end

  def video
    project = Project.new(video_url: params[:url])
    render json: project.video.to_json
  rescue VideoInfo::UrlError
    render json: nil
  end

  %w(embed video_embed).each do |method_name|
    define_method method_name do
      @title = resource.name
      render layout: 'embed'
    end
  end

  def embed_panel
    @title = resource.name
    render layout: false
  end

  protected

  def permitted_params
    params.permit(policy(resource).permitted_attributes)
  end

  def resource
    @project ||= (params[:permalink].present? ? Project.by_permalink(params[:permalink]).first! : Project.find(params[:id]))
  end

  def use_catarse_boostrap
    action_name == "new" || action_name == "create" ? 'catarse_bootstrap' : 'application'
  end
end

app/controllers/users/projects_controller.rb
class Users::ProjectsController < ApplicationController
  after_filter :verify_authorized, except: [:index]
  after_filter :verify_policy_scoped, only: [:index]

  inherit_resources
  actions :index
  belongs_to :user

  def index
    collection
    render layout: false
  end

  protected

  def policy_scope(scope)
    @_policy_scoped = true
    ProjectPolicy::UserScope.new(current_user, parent, scope).resolve
  end

  def collection
    @projects ||= policy_scope(end_of_association_chain).page(params[:page]).per(10)
  end

end

app/views/projects/_draft_warning.html.slim
br
- if policy(@project).update?
  #project_warning.bootstrap-alert
    .alert.alert-warning
      i Welcome to your project draft!
      #toggle_warning
        = link_to '(minimize)', '#'
      #project_warning_text
        br/
        br/
        | You can edit your project from the EDIT tab below this message. When you're done making your project more awesome, click "Update Information".
        br/
        | You'll find that you can also add rewards on this page; just click "Add Reward"! Adding rewards is highly recommended. Most successful campaigns offer tangible rewards for their backers.
        br/
        br/
        strong Whoa!
        br/
        | When you click the button below, you'll be sending in a <strong>DRAFT</strong> for the Funddit team to review. Based on the information provided, we're looking for a clearly articulated message that complies with our terms and conditions.
        | While we do not require a video, we <strong>HIGHLY RECOMMEND</strong> some form of multimedia outreach. This will dramatically increase your chances of getting funded. If you don't already have one, get started soon!
        br/
        br/
        - unless @project.user.wepay_account_id_string?
          | In the meantime please create a WePay account to collect funds!
          - redirect_uri = CatarseSettings[:base_url] + url_for(@user) + '/oauth'
          .bootstrap-twitter
            = button_to @project.user.wepay_authorization_url(redirect_uri), class: 'btn'
              | Create your WePay account!
        br/
        br/
        strong Getting started:
        br/
        | Check out: #{link_to 'How to produce a quality Funddit video', 'http://suporte.catarse.me/hc/pt-br/sections/200406978-Realizadores-Primeiros-passos', target: '__blank'}
      br/
      br/
      .bootstrap-twitter
        = link_to 'Send Draft', send_to_analysis_project_path(@project), class: 'btn btn-large'
        /!- if @project.user.wepay_account_id_string?
        /!  = link_to 'Send Draft', send_to_analysis_project_path(@project), class: 'btn btn-large'
        /!- else
        /!  = button_to 'Send Draft', send_to_analysis_project_path(@project), class: 'btn btn-large disabled', disabled: "disabled"
        /!  | You can't submit your draft until you create a wepay account!

- else
  #project_warning.bootstrap-alert
    .ale rt.alert-warning
      i Heads up! Your project is still a draft!.
      #toggle_warning
        = link_to '(minimize)', '#'
      #project_warning_text
        br/
        br/
        | This project still cannot receive financial contributions.

app/views/projects/_project_about.html.slim
.media
  - if resource.video_url.present?
    .video
      iframe src="#{@project.display_video_embed_url}" width="640" height="430" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen
  .social
    #project_share
      #facebook_share= render_facebook_like title: @project.name, href: project_by_slug_url(@project.permalink, locale: I18n.locale)
      ul
        li.embed
          = link_to '#embed', id: 'embed_link' do
            = image_tag "catarse/embed_icon19x9.png", title: t('.embed_title')
            = t('.embed')
        - if @project.online?
          li.reminder
            .bootstrap-twitter
                - if user_signed_in? && @project.user_already_in_reminder?(current_user.id)
                  small= link_to t('projects.reminder.deactive_btn'), reminder_project_path(@project), class: 'btn btn-small btn-extra-small', method: :delete
                - else
                  small= link_to t('projects.reminder.active_btn'), reminder_project_path(@project), class: 'btn btn-small btn-extra-small'
      #twitter_share= render_twitter(url: project_by_slug_url(permalink: @project.permalink), title: @project.name)
      .clearfix

.clearfix
#project_embed.hide data-path=embed_panel_project_path(@project)
  = image_tag "loading.gif", class: 'loader'
.text
  p
    = @project.about_html.html_safe

app/views/projects/_rejected_warning.html.slim
br
#project_warning.bootstrap-alert
  .alert.alert-warning
    i Sorry, this project was not accepted
    #toggle_warning
      = link_to '(minimize)', '#'
    #project_warning_text
      br/
      br/
      | We've determined that your project is not suitable for Funddit.
      br/
      br/
      | If you have any questions as to why your project was rejected, please send us an email. We encourage you to revisit your project and submit it again.
      br/

app/views/projects/embed.html.slim
#embed
  = render 'project', project: @project, embed_link: true

app/views/projects/embed_panel.html.slim
- box_width = "240px"
- box_height = "425px"
- video_width = "384px"
- video_height = "425px"
#project_box_embed
  iframe frameborder='0' height=box_height width=box_width src=embed_project_path(@project)
  form.html= text_area_tag 'project_box_embed_html', '<iframe frameborder="0" height="' + box_height + '" src="' + embed_project_url(@project) + '" width="' + box_width + '"></iframe>', readonly: true
#project_video_embed
  iframe frameborder='0' height=video_height width=video_width src=video_embed_project_path(@project)
  form.html= text_area_tag 'project_video_embed_html', '<iframe frameborder="0" height="' + video_height + '" src="' + video_embed_project_url(@project) + '" width="' + video_width + '"></iframe>', readonly: true
.clearfix

app/views/projects/show.html.slim
= javascript_include_tag "//www.google.com/jsapi", "chartkick"

= content_for :meta_tags do
  - if ['online', 'waiting_funds', 'successful'].include? @project.state
    meta name="robots" content="index, follow"
  - else
    meta name="robots" content="noindex, nofollow"

  - if @post
    meta name="description" content=@post.title
    meta property="og:title" content=@post.title
    meta property="og:description" content=@post.comment
    meta property="og:url" content=project_by_slug_url(@project.permalink, project_post_id: @post.id, locale: I18n.locale)
  - else
    meta name="description" content=@project.headline
    meta property="og:title" content=@project.name
    meta property="og:description" content=@project.headline
    meta property="og:url" content=project_by_slug_url(@project.permalink, locale: I18n.locale)
  meta property="og:type" content='cause'
  meta property="og:image" content=@project.display_image('project_thumb_facebook')
  meta property="og:site_name" content=CatarseSettings[:company_name]
  meta property="fb:admins" content="#{fb_admins}"

#page_content
  .container

    = render @project.state_warning_template

    #project_description
    .project_image
      = image_tag @project.display_image('project_thumb_small')
    .section_header
      h1= @project.name
      h4
        - if @project.user.school?
          = @project.user.school
        - else
          = t('.project_header.without_city')
        |&nbsp;
        = link_to(@project.category, explore_path(anchor: "by_category_id/#{@project.category_id}"))
        |&nbsp;
        = t('projects.index.box.by')
        |&nbsp;
        = link_to(@project.user.display_name, user_path(@project.user))
        |&nbsp;
        - @project.channels.each do |c|
          = link_to(c.name, root_url(subdomain: c.permalink), class: 'project-channel')
    .tab_container
      nav#project_menu
        = link_to '#about', 'id' => 'about_link', 'class' => 'selected', 'data-target' => '#project_about.content' do
          = t('.menu.about')
        = link_to '#posts', 'id' => 'posts_link', 'data-target' => '#project_posts' do
          = t('.menu.posts')
          span.count=" (#{@posts_count})"
        = link_to '#contributions', 'id' => 'contributions_link', 'data-target' => '#project_contributions' do
          = t('.menu.contributions')
          span.count=" (#{@project.total_contributions})"
        = link_to '#comments', 'id' => 'comments_link', 'data-target' => '#project_comments' do
          = t('.menu.comments')
          | &nbsp; (
          / we need to remove the locale from the url
          fb:comments-count href="#{request.base_url}/#{request.fullpath.split('/')[2]}"
          | )
        - if policy(@project).update?
          = link_to '#edit', 'id' => 'edit_link', 'data-target' => '#project_edit' do
            = t('.menu.edit')
          = link_to '#reports', 'id' => 'reports_link', 'data-target' => '#project_reports' do
            = t('.menu.reports')
          = link_to '#metrics', id: 'metrics_link', data: {target: '#project_metrics'} do
            = t('.menu.metrics')
    .main
      #project_content
        - if policy(@project).update?
          #project_reports.content.hide
            = render 'project_reports'
          #project_edit.content.hide
            = render 'project_edit'

        #project_posts.content.hide[data-path=project_posts_path(project_id: @project.id)]
          - if policy(@project).update?
            = render template: 'projects/posts/new'
          .results data-skiptab=""
          .clearfix
          #posts-loading.loading= image_tag "loading.gif"
        #project_contributions.content.hide[data-path=project_contributions_path(project_id: @project.id)]
          - if policy(@project).update?
            = radio_button_tag(:contribution_state, "available_to_count", checked: true)
            = label_tag(:contribution_state, t('.contribution_states.confirmed'))
            = radio_button_tag(:contribution_state, "waiting_confirmation")
            = label_tag(:contribution_state, t('.contributions_states.pending'))
          .results data-skiptab=""
          .clearfix
          #contributions-loading.loading= image_tag "loading.gif"
        #project_comments.content.hide
        #project_about.content= render 'project_about'
        #project_metrics.content.hide[data-path=metrics_project_path(id: @project.id)]
          .results
          .clearfix
          #metrics-loading.loading= image_tag "loading.gif"

      .clearfix
    .sidebar
      .info
        #statistics
          .statistics
            .item.contributions
              p= @project.total_contributions
              em= t('.sidebar.contributions')
            .item.goal
              p= @project.display_goal
              em= t('.sidebar.goal', total: @project.display_goal).html_safe
            .item.time
              - if @project.draft? || @project.rejected?
                p= @project.online_days
                em #{@project.online_days} #{pluralize_without_number(@project.online_days, I18n.t('datetime.prompts.day').downcase)} #{pluralize_without_number(@project.online_days, t('remaining_singular'), t('remaining_plural'))}
              - else
                p= @project.remaining_days
                em #{@project.time_to_go[:unit].capitalize} #{pluralize_without_number(@project.time_to_go[:time], t('remaining_singular'), t('remaining_plural'))}

          #condition[class="#{@project.display_status}"]
            p
              = t(".contribute_project.display_status.#{@project.display_status}", goal: @project.display_goal, date: @project.display_expires_at)
          - if @project.accept_contributions?
            #pledge
              = form_tag(new_project_contribution_path(@project), method: :get, id: 'contribute_project_form') do
                fieldset
                  = submit_tag t('.contribute_project.submit'), disabled: (not @project.online?)
        #creator_profile
          h3= t('.project_by')
          .avatar = @project.user.display_image_html width: 80, height: 80
          .personal_info
            p.name
             = link_to @project.user.display_name, user_path(@project.user)
            #bio
              p= @project.user.bio
          #city
            p.contribution= t('.count_contributed_projects', total: @project.user.total_contributed_projects)
            p.city
              | #{@project.user.address_city}
        .user_social
          ul
            - if @project.user.facebook_link.present?
              li
                = link_to "Perfil no facebook", @project.user.facebook_link, target: '_blank', class: 'facebook'
            - if @project.user.twitter_link
              li
                = link_to "Perfil no twitter", @project.user.twitter_link, target: '_blank', class: 'twitter'
            - if @project.user.email
              li
                = mail_to @project.user.email, @project.user.email, target: '_blank', class: 'email'
            - if @project.user.other_link
              li.other
                = link_to @project.user.other_link, @project.user.other_link, target: '_blank'

        .clearfix
        - if policy(@project).update?
          .bootstrap-twitter.bootstrap-form
            .alert.alert-info
              h4.alert-header= t('.no_rewards_warning_title')
              p style="margin:0; padding:0;"
                = t('.no_rewards_warning')
              br/
              .new_reward_content.hide
                = image_tag 'loading.gif'

            .clearfix
            = link_to t('.menu.add_reward'), 'javascript:void(0);', data: {target: '.new_reward_content', path: new_project_reward_path(@project)}, class: 'btn btn-success pull-right show_reward_form'
            .clearfix

            br/
            /.skull-modal.new_reward_content.hide
              .skull-modal-header
                h3= t('projects.rewards.new_reward')
                a class='skull-modal-close' href='javascript:void(0);' &times;
              .skull-modal-body
                = image_tag 'loading.gif'
        #rewards[data-can_update="#{policy(@project).update?}" data-index_path=project_rewards_path(@project)]
          .reward-loader= image_tag 'loading.gif'
        .funding_period_title
          = t('.funding_period')
        .funding_period
          = "#{@project.display_online_date} - #{@project.display_expires_at} (#{t('datetime.distance_in_words.x_days', count: @project.online_days)})"

    .clearfix