config/routes.rb
Catarse::Application.routes.draw do
  def ssl_options
    if Rails.env.production? && CatarseSettings.get_without_cache(:secure_host)
      {protocol: 'https', host: CatarseSettings.get_without_cache(:secure_host)}
    else
      {}
    end
  end

  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  devise_for(
    :users,
    {
      path: '',
      path_names:   { sign_in: :login, sign_out: :logout, sign_up: :sign_up },
      controllers:  { omniauth_callbacks: :omniauth_callbacks, passwords: :passwords },
      defaults: ssl_options
    }
  )

  devise_scope :user do
    post '/sign_up', {to: 'devise/registrations#create', as: :sign_up}.merge(ssl_options)
  end

  get '/thank_you' => "static#thank_you"
  match 'users/:user_id/oauth', to: 'users#oauth', via: :all


  filter :locale, exclude: /\/auth\//

  #mount CatarsePaypalExpress::Engine => "/", as: :catarse_paypal_express
  #mount CatarseMoip::Engine => "/", as: :catarse_moip
  mount CatarseCredits::Engine => "/", as: :catarse_credits
  mount CatarsePagarme::Engine => "/", as: :catarse_pagarme
  mount CatarseWepay::Engine => "/", as: :catarse_wepay

  get '/post_preview' => 'post_preview#show', as: :post_preview
  resources :auto_complete_projects, only: [:index]
  resources :projects, only: [:index, :create, :update, :new, :show] do
    resources :posts, controller: 'projects/posts', only: [ :index, :create, :destroy ]
    resources :rewards, only: [ :index, :create, :update, :destroy, :new, :edit ] do
      member do
        post 'sort'
      end
    end
    resources :contributions, {controller: 'projects/contributions'}.merge(ssl_options) do
      member do
        put 'credits_checkout'
      end
    end
    collection do
      get 'video'
    end
    member do
      get :reminder, to: 'projects/reminders#create'
      delete :reminder, to: 'projects/reminders#destroy'
      get :metrics, to: 'projects/metrics#index'
      put 'pay'
      get 'embed'
      get 'video_embed'
      get 'embed_panel'
      get 'send_to_analysis'
    end
  end
  resources :users do
    resources :projects, controller: 'users/projects', only: [ :index ]
    resources :credit_cards, controller: 'users/credit_cards', only: [ :destroy ]
    member do
      get :unsubscribe_notifications
      get :credits
      get :reactivate
    end
    resources :contributions, controller: 'users/contributions', only: [:index] do
      member do
        get :request_refund
      end
    end

    resources :unsubscribes, only: [:create]
    member do
      get 'projects'
      put 'unsubscribe_update'
      put 'update_email'
      put 'update_password', ssl_options
    end
  end

  get "/terms-of-use" => 'high_voltage/pages#show', id: 'terms_of_use'
  get "/privacy-policy" => 'high_voltage/pages#show', id: 'privacy_policy'
  get "/start" => 'high_voltage/pages#show', id: 'start'


  # Channels
  constraints SubdomainConstraint do
    namespace :channels, path: '' do

      namespace :admin do
        namespace :reports do
          resources :subscriber_reports, only: [ :index ]
        end
        resources :posts
        resources :partners
        resources :followers, only: [ :index ]
      end

      resources :posts
      get '/', to: 'profiles#show', as: :profile
      get '/how-it-works', to: 'profiles#how_it_works', as: :about
      resource :profile
      # NOTE We use index instead of create to subscribe comming back from auth via GET
      resource :channels_subscriber, only: [:show, :destroy], as: :subscriber
    end
  end

  # Root path should be after channel constraints
  root to: 'projects#index'

  get "/explore" => "explore#index", as: :explore

  namespace :reports do
    resources :contribution_reports_for_project_owners, only: [:index]
  end

  # Feedback form
  resources :feedbacks, only: [:create]

  namespace :admin do
    resources :projects, only: [ :index, :update, :destroy ] do
      member do
        put 'approve'
        put 'reject'
        put 'push_to_draft'
        put 'push_to_trash'
      end
    end

    resources :statistics, only: [ :index ]
    resources :financials, only: [ :index ]

    resources :contributions, only: [ :index, :update, :show ] do
      member do
        get :second_slip
        put 'confirm'
        put 'pendent'
        put 'change_reward'
        put 'refund'
        put 'hide'
        put 'cancel'
        put 'push_to_trash'
      end
    end
    resources :users, only: [ :index ]

    namespace :reports do
      resources :contribution_reports, only: [ :index ]
    end
  end

  get "/:permalink" => "projects#show", as: :project_by_slug

end

app/models/concerns/contribution/custom_validators.rb
module Contribution::CustomValidators
  extend ActiveSupport::Concern

  included do
    validate :reward_must_be_from_project
    validate :value_must_be_at_least_rewards_value
    validate :should_not_contribute_if_maximum_contributions_been_reached, on: :create
    validate :project_should_be_online, on: :create

    def reward_must_be_from_project
      return unless reward
      errors.add(:reward, I18n.t('contribution.reward_must_be_from_project')) unless reward.project == project
    end

    def value_must_be_at_least_rewards_value
      return unless reward
      errors.add(:value, I18n.t('contribution.value_must_be_at_least_rewards_value', minimum_value: reward.display_minimum)) unless value.to_f >= reward.minimum_value
    end

    def should_not_contribute_if_maximum_contributions_been_reached
      return unless reward && reward.maximum_contributions && reward.maximum_contributions > 0
      errors.add(:reward, I18n.t('contribution.should_not_contribute_if_maximum_contributions_been_reached')) if reward.sold_out?
    end

    def project_should_be_online
      return if project && project.online?
      errors.add(:project, I18n.t('contribution.project_should_be_online'))
    end

  end
end

app/models/concerns/contribution/payment_engine_handler.rb
module Contribution::PaymentEngineHandler
  extend ActiveSupport::Concern

  included do

    delegate :can_do_refund?, to: :payment_engine

    def payment_engine
      PaymentEngines.find_engine(self.payment_method) || PaymentEngines::Interface.new
    end

    def review_path
      payment_engine.review_path(self)
    end

    def direct_refund
      payment_engine.direct_refund(self)
    end

    def second_slip_path
      payment_engine.try(:second_slip_path, self)
    end

    def can_generate_second_slip?
      payment_engine.try(:can_generate_second_slip?)
    end

    def update_current_billing_info
      self.address_street = user.address_street
      self.address_number = user.address_number
      self.address_neighbourhood = user.address_neighbourhood
      self.address_zip_code = user.address_zip_code
      self.address_city = user.address_city
      self.address_state = user.address_state
      self.address_phone_number = user.phone_number
      self.payer_document = user.cpf
      self.payer_name = user.display_name
    end

    def update_user_billing_info
      user.update_attributes({
        address_street: address_street.presence || user.address_street,
        address_number: address_number.presence || user.address_number,
        address_neighbourhood: address_neighbourhood.presence || user.address_neighbourhood,
        address_zip_code: address_zip_code.presence|| user.address_zip_code,
        address_city: address_city.presence || user.address_city,
        address_state: address_state.presence || user.address_state,
        phone_number: address_phone_number.presence || user.phone_number,
        cpf: payer_document.presence || user.cpf
      })
    end

  end
end

app/models/concerns/contribution/payment_methods.rb
module Contribution::PaymentMethods
  extend ActiveSupport::Concern

  included do
    def is_wepay?
      payment_method.try(:downcase) == 'wepay'
    end

    def is_pagarme?
      payment_method.try(:downcase) == 'pagarme'
    end

    def is_credit_card?
      payment_choice.try(:downcase) == 'cartaodecredito'
    end
  end
end

app/models/concerns/contribution/state_machine_handler.rb
module Contribution::StateMachineHandler
  extend ActiveSupport::Concern

  included do
    state_machine :state, initial: :pending do
      state :pending, value: 'pending'
      state :waiting_confirmation, value: 'waiting_confirmation'
      state :confirmed, value: 'confirmed'
      state :canceled, value: 'canceled'
      state :refunded, value: 'refunded'
      state :requested_refund, value: 'requested_refund'
      state :refunded_and_canceled, value: 'refunded_and_canceled'
      state :deleted, value: 'deleted'
      state :invalid_payment, value: 'invalid_payment'

      event :push_to_trash do
        transition all => :deleted
      end

      event :pendent do
        transition all => :pending
      end

      event :waiting do
        transition pending: :waiting_confirmation
      end

      event :invalid do
        transition all => :invalid_payment
      end

      event :confirm do
        transition [:pending, :confirmed, :waiting_confirmation, :canceled, :deleted] => :confirmed
      end

      event :cancel do
        transition all => :canceled
      end

      event :request_refund do
        transition confirmed: :requested_refund, if: ->(contribution){
          contribution.user.credits >= contribution.value && !contribution.credits
        }
      end

      event :refund do
        transition [:requested_refund, :confirmed] => :refunded
      end

      event :hide do
        transition all => :refunded_and_canceled
      end

      after_transition do |contribution, transition|
        contribution.notify_observers :"from_#{transition.from}_to_#{transition.to}"

        to_column = "#{transition.to}_at".to_sym
        if contribution.has_attribute?(to_column)
          contribution.update_attribute to_column, DateTime.now
        end
      end

      after_transition any => [:refunded_and_canceled] do |contribution, transition|
        contribution.notify_to_contributor :refunded_and_canceled
      end
    end
  end
end

app/controllers/admin/contributions_controller.rb
class Admin::ContributionsController < Admin::BaseController
  layout 'catarse_bootstrap'
  has_scope :by_id, :by_user_id, :by_key, :user_name_contains, :user_email_contains, :payer_email_contains, :project_name_contains, :confirmed, :with_state, :by_value, :by_payment_id
  has_scope :credits, type: :boolean
  has_scope :between_values, using: [ :start_at, :ends_at ], allow_blank: true
  before_filter :set_title

  def self.contribution_actions
    %w[confirm pendent refund hide cancel push_to_trash].each do |action|
      define_method action do
        if resource.send(action)
          flash[:notice] = I18n.t("admin.contributions.messages.successful.#{action}")
        else
          flash[:notice] = t("activerecord.errors.models.contribution")
        end
        redirect_to admin_contributions_path(params[:local_params])
      end
    end
  end
  contribution_actions

  def change_reward
    resource.change_reward! params[:reward_id]
    flash[:notice] = I18n.t('admin.contributions.messages.successful.change_reward')
    redirect_to admin_contributions_path(params[:local_params])
  end

  protected
  def set_title
    @title = t("admin.contributions.index.title")
  end

  def collection
    @contributions = apply_scopes(end_of_association_chain).without_state('deleted').order("contributions.created_at DESC").page(params[:page])
  end
end

app/controllers/projects/contributions_controller.rb
class Projects::ContributionsController < ApplicationController
  inherit_resources
  actions :index, :show, :new, :update, :review, :create
  skip_before_filter :force_http
  skip_before_filter :verify_authenticity_token, only: [:moip]
  has_scope :available_to_count, type: :boolean
  has_scope :with_state
  has_scope :page, default: 1
  after_filter :verify_authorized, except: [:index]
  belongs_to :project
  before_filter :detect_old_browsers, only: [:new, :create]

  helper_method :avaiable_payment_engines

  def edit
    authorize resource
    if resource.reward.try(:sold_out?)
      flash[:alert] = t('.reward_sold_out')
      return redirect_to new_project_contribution_path(@project)
    end
  end

  def update
    authorize resource
    resource.update_attributes(permitted_params[:contribution])
    resource.update_user_billing_info
    render json: {message: 'updated'}
  end

  def index
    render collection
  end

  def show
    authorize resource
    @title = t('projects.contributions.show.title')
  end

  def new
    @contribution = Contribution.new(project: parent, user: current_user)
    authorize @contribution

    @title = t('projects.contributions.new.title', name: @project.name)
    empty_reward = Reward.new(minimum_value: 0, description: t('projects.contributions.new.no_reward'))
    @rewards = [empty_reward] + @project.rewards.remaining.order(:minimum_value)

    # Select
    if params[:reward_id] && (@selected_reward = @project.rewards.find params[:reward_id]) && !@selected_reward.sold_out?
      @contribution.reward = @selected_reward
      @contribution.value = "%0.0f" % @selected_reward.minimum_value
    end
  end

  def create
    @title = t('projects.contributions.create.title')
    @contribution = Contribution.new(params[:contribution].merge(user: current_user, project: parent))
    @contribution.reward_id = nil if params[:contribution][:reward_id].to_i == 0
    authorize @contribution
    create! do |success,failure|
      failure.html do
        flash[:alert] = resource.errors.full_messages.to_sentence
        return redirect_to new_project_contribution_path(@project)
      end
      success.html do
        resource.update_current_billing_info
        flash[:notice] = nil
        session[:thank_you_contribution_id] = @contribution.id
        return redirect_to edit_project_contribution_path(project_id: @project.id, id: @contribution.id)
      end
    end
    @thank_you_id = @project.id
  end

  protected
  def permitted_params
    params.permit(policy(resource).permitted_attributes)
  end

  def avaiable_payment_engines
    engines = []

    if resource.value < 0
      engines.push PaymentEngines.find_engine('Credits')
    else
      if parent.using_pagarme?
        engines.push PaymentEngines.find_engine('Pagarme')
      else
        engines = PaymentEngines.engines.inject([]) do |total, item|
          if item.name != 'Credits' && item.name != 'Pagarme'
            total << item
          end
#          if item.name == 'Credits' && current_user.credits > 0
#            total << item
#          elsif !item.name.match(/(Credits|Pagarme)/)
#            total << item
#          end

          total
        end
      end
    end

    @engines ||= engines
  end

  def collection
    @contributions ||= apply_scopes(end_of_association_chain).available_to_display.order("confirmed_at DESC").per(10)
  end
end

app/controllers/users/contributions_controller.rb
class Users::ContributionsController < ApplicationController
  after_filter :verify_authorized, except: [:index]
  after_filter :verify_policy_scoped, only: [:index]
  inherit_resources
  defaults resource_class: Contribution
  belongs_to :user
  actions :index

  def index
    collection
    render layout: false
  end

  def request_refund
    authorize resource
    if resource.value > resource.user.user_total.credits || !resource.request_refund
      flash[:failure] = I18n.t('users.credits.index.insufficient_credits')
    else
      flash[:notice] = I18n.t('users.credits.index.refunded')
    end

    redirect_to user_path(parent, anchor: 'credits')
  end

  protected
  def policy_scope(scope)
    @_policy_scoped = true
    ContributionPolicy::UserScope.new(current_user, parent, scope).resolve
  end

  def collection
    @contributions ||= policy_scope(end_of_association_chain).order("created_at DESC, confirmed_at DESC").includes(:user, :reward, project: [:user, :category, :project_total]).page(params[:page]).per(10)
  end
end

app/views/catarse_bootstrap/admin/contributions/index.html.slim
= render 'shared/header_bootstrap_v1'
.row.admin.admin-contributions
  h1
    = @title = t('channels.admin.management.title')
    ' :
  h3 = t('channels.admin.filter.title')
  = simple_form_for '', url: admin_contributions_path, method: :get do |form|
    .row
      .large-1.columns
        = form.input :by_id, as: :integer, label: t('.id')
      .large-2.columns
        = form.input :by_user_id, as: :integer, label: t('.user_id')
      .large-2.columns
        = form.input 'between_values[start_at]', as: :integer, label: t(".between_values")
      .large-2.columns.no-label
        = form.input 'between_values[ends_at]', as: :integer, label: ''
      .large-3.columns
        = form.input :payer_email_contains, as: :string, label: t('.payer_email')
      .large-2.columns
        = form.input :by_payment_id, as: :string, label: t('.payment_id')
    .row
      .large-2.columns
        = form.input :with_state, collection: Contribution.state_names, label: t('channels.admin.filter.with_state'), as: :select, selected: params[:with_state], include_blank: true
      .large-3.columns
        = form.input :project_name_contains, as: :string, label: t('.project')
      .large-2.columns
        = form.input :user_name_contains, as: :string, label: t('.user')
      .large-2.columns
        = form.input :by_key, as: :string, label: t('.key')
      .large-3.columns
        = form.input :user_email_contains, as: :string, label: t('.user_email')
    .row
      .large-9.columns
        = form.input :credits, as: :boolean, label: t('.credits')
      .large-2.columns
        = form.button :submit, t('channels.admin.filter.submit'), class: 'button medium negative'

  = paginate @contributions
  - if @contributions.empty?
    = t('.no_contributions')
  - else
    table.admin-contributions
      thead
        tr
          th= t('.contribution')
          th= t('.project')
          th= t('.user')
          th= t('.value')
          th= t('.payment_tax')
          th= t('.reward')
          th= t('.key')
          th= t('.anonymous')
          th= t('.credits')
          th= t('.state')
          th
      tbody
        - @contributions.includes(:project, :user, :reward).each do |contribution|
          tr id=contribution.id class=cycle("even", "odd")
            td
              = link_to contribution.id, admin_contribution_path(contribution)
            td.project_info title=contribution.project.name
              = link_to project_by_slug_path(permalink: contribution.project.permalink) do
                = image_tag contribution.project.display_image, class: 'project_img'
            td.user_info title=contribution.user.display_name
              = link_to user_path(contribution.user) do
                = image_tag contribution.user.display_image, class: 'user_img'
              .user_id= best_in_place [:admin, contribution], :user_id, method: :put, type: :input
            td= best_in_place [:admin, contribution], :value, method: :put, type: :input
            td= contribution.payment_service_fee
            td.reward.large-1.columns.project-events-dropdown title=("#{contribution.reward.display_minimum} - #{contribution.reward.description}" if contribution.reward)
              - if contribution.reward
                span = contribution.reward.display_minimum
              - else
                | -
              .btn-group
                = link_to 'javascript:void(0);', data: {toggle: 'dropdown'}, class: 'btn btn-mini dropdown-toggle' do
                  span.caret
                ul.dropdown
                  li title=("#{t('.no_reward')}" ) = link_to t('.no_reward'), change_reward_admin_contribution_path(contribution, reward_id: nil), method: :put
                  - contribution.available_rewards.each do |reward|
                    li title=("#{reward.display_minimum} - #{reward.description}" ) = link_to reward.minimum_value, change_reward_admin_contribution_path(contribution, reward_id: reward.id, local_params: params), method: :put

            td.key= contribution.key
            td.checkbox= best_in_place [:admin, contribution], :anonymous, method: :put, type: :checkbox, collection: [t('no'), t('yes')]
            td= (contribution.credits ? t('yes') : t('no'))
            td= contribution.state
            td.large-1.columns.project-events-dropdown
              .btn-group
                = link_to 'javascript:void(0);', data: {toggle: 'dropdown'}, class: 'btn btn-mini dropdown-toggle' do
                  span.caret
                ul.dropdown
                  - if contribution.confirmed?
                    li= link_to t('admin.contributions.index.unconfirm_contribution'), pendent_admin_contribution_path(contribution, local_params: params), method: :put
                  - else
                    li= link_to t('admin.contributions.index.confirm_contribution'), confirm_admin_contribution_path(contribution, local_params: params), method: :put
                  - if contribution.requested_refund? or contribution.confirmed?
                    li= link_to t('admin.contributions.index.refund_contribution'), refund_admin_contribution_path(contribution, local_params: params), method: :put
                  li= link_to t('admin.contributions.index.refund_and_hide'), hide_admin_contribution_path(contribution, local_params: params), method: :put
                  li= link_to t('admin.contributions.index.cancel'), cancel_admin_contribution_path(contribution, local_params: params), method: :put
                  li= link_to t('admin.contributions.index.push_to_trash'), push_to_trash_admin_contribution_path(contribution, local_params: params), method: :put
                  - if (contribution.waiting_confirmation? || contribution.pending? || contribution.canceled?) && contribution.slip_payment? && contribution.can_generate_second_slip?
                    li= link_to 'Segunda via de boleto', contribution.second_slip_path, target: '__blank', method: :put
= paginate @contributions

= render 'shared/footer_bootstrap_v1'

app/views/catarse_bootstrap/admin/contributions/show.html.slim
= render 'shared/header_bootstrap_v1'

.row
  h3= t('.contribution_info', key: resource.key)
  p
    strong= t('.payment_method')
    | &nbsp;
    = resource.payment_method
  p
    strong= t('.payment_fee')
    | &nbsp;
    = number_to_currency resource.payment_service_fee, unit: 'R$', precision: 2, delimiter: '.'
  p
    strong= t('.payment_id')
    | &nbsp;
    = resource.payment_id
  p
    strong= t('.payer_email')
    | &nbsp;
    = resource.payer_email
  p
    strong= t('.user_email')
    | &nbsp;
    = resource.user.email
  p
    strong= t('.payment_choice')
    | &nbsp;
    = resource.payment_choice
  p
    strong= t('.created_at')
    | &nbsp;
    = l(resource.created_at)

= render 'shared/footer_bootstrap_v1'